version: '3.8'

services:

    frontend:
        container_name: front
        build:
            context: ./
            dockerfile: Dockerfile.frontend
        volumes:
            # NOTE: Protect the 'node_modules' folder of being erased
            - '/usr/src/app/node_modules'
            - './:/usr/src/app'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        command: npm start
